package pokemon_battle;

public enum TypeAttack {
	NORMAL, FIRE, ICE, WATER, ELECTRIC, PLANT, FIGHTER, POISONOUS,
	OVERLAND, FLIER, PSYCHIC, INSECT, ROCK, GHOST, DRAGON, NOCTURNAL,
	METALLIC;
}
